/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEmoji: typeof import('./../components/BaseEmoji.vue')['default']
    BaseModal: typeof import('./../components/BaseModal.vue')['default']
    Col: typeof import('./../components/Layout/Col.vue')['default']
    DrawCanvas: typeof import('./../components/DrawCanvas.vue')['default']
    DrawPanel: typeof import('./../components/DrawPanel.vue')['default']
    DrawTools: typeof import('./../components/DrawTools.vue')['default']
    EmojiFiles: typeof import('./../components/EmojiFiles.vue')['default']
    EmojiList: typeof import('./../components/EmojiList.vue')['default']
    EmojiSelection: typeof import('./../components/EmojiSelection.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlackEmojiModal: typeof import('./../components/SlackEmojiModal.vue')['default']
    TextEmoji: typeof import('./../components/TextEmoji.vue')['default']
  }
}
