/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./../components/Base/BaseAvatar.vue')['default']
    BaseEmoji: typeof import('./../components/Base/BaseEmoji.vue')['default']
    BaseLoader: typeof import('./../components/Base/BaseLoader.vue')['default']
    BaseModal: typeof import('./../components/Base/BaseModal.vue')['default']
    Col: typeof import('./../components/Layout/Col.vue')['default']
    CommunityBrowseModal: typeof import('./../components/Draw/CommunityBrowseModal.vue')['default']
    CommunityMineModal: typeof import('./../components/Draw/CommunityMineModal.vue')['default']
    CommunitySaveModal: typeof import('./../components/Draw/CommunitySaveModal.vue')['default']
    CommunityTools: typeof import('./../components/Draw/CommunityTools.vue')['default']
    DragAndDrop: typeof import('./../components/Layout/DragAndDrop.vue')['default']
    DrawCanvas: typeof import('./../components/Draw/DrawCanvas.vue')['default']
    DrawPanel: typeof import('./../components/Draw/DrawPanel.vue')['default']
    DrawTools: typeof import('./../components/Draw/DrawTools.vue')['default']
    DrawUndoRedo: typeof import('./../components/Draw/DrawUndoRedo.vue')['default']
    EmojiFiles: typeof import('./../components/Draw/EmojiFiles.vue')['default']
    EmojiList: typeof import('./../components/Draw/EmojiList.vue')['default']
    EmojiPreviewCanvas: typeof import('./../components/Draw/EmojiPreviewCanvas.vue')['default']
    EmojiSelection: typeof import('./../components/Draw/EmojiSelection.vue')['default']
    HeaderTabs: typeof import('./../components/Layout/HeaderTabs.vue')['default']
    IcantGenerator: typeof import('./../components/Icant/IcantGenerator.vue')['default']
    OptionsTools: typeof import('./../components/Draw/OptionsTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcut: typeof import('./../components/Draw/Shortcut.vue')['default']
    SlackEmojiModal: typeof import('./../components/Draw/SlackEmojiModal.vue')['default']
    Test: typeof import('./../components/Draw/Test.vue')['default']
    TextPanel: typeof import('./../components/Draw/TextPanel.vue')['default']
    TextTools: typeof import('./../components/Draw/TextTools.vue')['default']
    ThemeTools: typeof import('./../components/Draw/ThemeTools.vue')['default']
    Tools: typeof import('./../components/Draw/Tools.vue')['default']
    UserAvatar: typeof import('./../components/User/UserAvatar.vue')['default']
    UserLogin: typeof import('./../components/User/UserLogin.vue')['default']
    UserMenu: typeof import('./../components/User/UserMenu.vue')['default']
    WritePanel: typeof import('./../components/Write/WritePanel.vue')['default']
  }
}
