/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseEmoji: typeof import('./../components/Base/BaseEmoji.vue')['default']
    BaseModal: typeof import('./../components/Base/BaseModal.vue')['default']
    Col: typeof import('./../components/Layout/Col.vue')['default']
    DrawCanvas: typeof import('./../components/Draw/DrawCanvas.vue')['default']
    DrawPanel: typeof import('./../components/Draw/DrawPanel.vue')['default']
    DrawTools: typeof import('./../components/Draw/DrawTools.vue')['default']
    DrawUndoRedo: typeof import('./../components/Draw/DrawUndoRedo.vue')['default']
    EmojiFiles: typeof import('./../components/Draw/EmojiFiles.vue')['default']
    EmojiList: typeof import('./../components/Draw/EmojiList.vue')['default']
    EmojiSelection: typeof import('./../components/Draw/EmojiSelection.vue')['default']
    HeaderTabs: typeof import('./../components/Layout/HeaderTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcut: typeof import('./../components/Draw/Shortcut.vue')['default']
    SlackEmojiModal: typeof import('./../components/Draw/SlackEmojiModal.vue')['default']
    TextPanel: typeof import('./../components/Draw/TextPanel.vue')['default']
    TextTools: typeof import('./../components/Draw/TextTools.vue')['default']
    ThemeTools: typeof import('./../components/Draw/ThemeTools.vue')['default']
    Tools: typeof import('./../components/Draw/Tools.vue')['default']
    UserAvatar: typeof import('./../components/User/UserAvatar.vue')['default']
    UserLogin: typeof import('./../components/User/UserLogin.vue')['default']
    UserMenu: typeof import('./../components/User/UserMenu.vue')['default']
  }
}
