#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Redirect stdin to /dev/tty
# exec < /dev/tty

set -x

yarn type-check && npm version --patch && yarn build && git add docs/ && git commit -m "deploy: v$(node -p "require('./package.json').version")"
