#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Redirect stdin to /dev/tty
# exec < /dev/tty

set -x

# yarn version-patch && git add package.json && yarn build && git add docs/ && git commit -m "deploy: v$(node -p "require('./package.json').version")"
